### ISSUE TITLE
Создать скелет Java проекта на интерфейсах

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#11]
Создать проект на Gradle или Maven и набросать интерфейсы на основе диаграммы классов.

**Comment by codename-art** [comment]
@kkrupovich 
Беру задачу на 2 дня
BLOCK #23984977

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 165.00000 UTDEV.SKILL


Проверка 31.01 вечером

**Comment by codename-art** [comment]
@kkrupovich для работы с этой задачей, так же выполнил #9 и #16.
Создал основу в соответствии с имеющейся диаграммой классов. Формулировка задачи оказалась слишком обширной, для дальнейшей работы создам более конкретные задачи.

**Comment by kkrupovich** [comment]
BLOCK #24030476

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 165.00000 UTDEV

@codename-art ты закроешь? или если #check# будем закрывать по workflow при регистрации оплаты? Я уже в контексте [UT-WORKS](https://github.com/u-transnet/UT-WORKS/issues/2) задумываюсь ;)
