### ISSUE TITLE
Парсинг входных данных и инициализация инфраструктуры

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#12]
Продолжение #3

**Comment by codename-art** [comment]
@kkrupovich 
Беру задачу на день
BLOCK #24211895

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 07.02 вечером

**Comment by kkrupovich** [comment]
Логично :)

**Comment by codename-art** [comment]
@kkrupovich Добавил создание Маршрутной карты из входных данных, реализовал ее структуру. На данном этапе этого достаточно для  продолжения задачи #23

**Comment by kkrupovich** [comment]
@codename-art снимаем blocking? 
PS: Надо придумать что делать с заскилованными задачами, которые требуют доп. трудозатрат, либо трансформируются в процессе реализации в аналоги epic - видимо, их не имеет смысла маркировать как paid даже в случае промежуточной компенсации скилла за этап работ, это раз. А два - возможно, нужно расширение бизнес-процесса skill-dev @EvgeniyPolyakov @jackal1527 `TBD воткнуть куда-то в истории ut-works`

**Comment by cptn-solo** [comment]
@codename-art если будем продлевать - не забыть снять #paid#
BLOCK #24422386

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV

**Comment by codename-art** [comment]
соответствующие задачи в Jira: https://u-trans.atlassian.net/browse/UK-4 https://u-trans.atlassian.net/browse/UK-5
