### ISSUE TITLE
Wrapper для graphenej

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#13]
Обертка для вызова API блокчейна (#9) позволит абстрагироваться от конкретной реализации для упрощения возможной миграции и тестирования

**Comment by codename-art** [comment]
@kkrupovich 
Задача перетекла из #18 и частично реализована:
сделана абстракция, позволяющая отделить симулятор от конкретной реализации блокчейна. Благодаря этому симулятор может работать как с нашим графеном, так с другим блокчейном. В том числе, можно реализовать внешнее API поверх обычной субд, что позволит проводить тестирование.

BLOCK #24083641

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 02.02 вечером

**Comment by kkrupovich** [comment]
@codename-art 
BLOCK #24088276

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
