### ISSUE TITLE
Перенести документацию в репозиторий

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#14]
Перенести документ архитектуры #1 решения в формате md в репозиторий

**Comment by codename-art** [comment]
https://github.com/u-transnet/transnet-simulator/wiki

**Comment by kkrupovich** [comment]
@codename-art по-моему просто супер. И расширяется вполне понятно, имхо. Думаешь надо в мастер втащить? или не горит?

**Comment by codename-art** [comment]
@kkrupovich Стоит мержить, чтобы отдельно ветка не висела. Далее буду делать фичи через git flow
