### ISSUE TITLE
Сделать первоначальную настройку Gradle пректа

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#16]

**Comment by codename-art** [comment]
@kkrupovich Создал первоначальную структуру:
корневой проект и проект симулятора. Такая структура позволит добавлять в репозиторий другие связанные проекты, например, утилиту просмотра логов.

**Comment by kkrupovich** [comment]
@codename-art Собралось? какие-то базовые штуки не пробовал через API делать? Интересно посмотреть на консольную java-graphene связку.
@Arteg0r а ты не искал в итоге Opensource minecraft-клонов?

**Comment by codename-art** [comment]
@kkrupovich Еще не делал вызовов через API, эти задачи сделаю в репозитории graphenej, но на этой неделе ими заниматься пока не буду.
