### ISSUE TITLE
Реализовать основной цикл

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#18]
Поскольку необходимо симулировать движение ОФИ, для работы симулятора будем использовать шаблон Game Loop http://gameprogrammingpatterns.com/game-loop.html

**Comment by codename-art** [comment]
@kkrupovich 
BLOCK #24041124

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 01.02 вечером

**Comment by codename-art** [comment]
@kkrupovich 
Реализован основной цикл, вызывающий на каждой итерации обновление акторов. Так же цикл разгребает очередь сообщений, в который пользователь может загружать новых клиентов с маршрутными картами.
Акторы могут взаимодействовать с блокчейном и имеют механизм реагирования на транзакции.

**Comment by kkrupovich** [comment]
@codename-art 
BLOCK #24088439

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV

**Comment by kkrupovich** [comment]
@codename-art 
> Акторы могут взаимодействовать с блокчейном и имеют механизм реагирования на транзакции.

Ключевое :) кстати, мне кажется, я знаю где подсмотреть обсуждения по генерации потока траназкций - в истории о нагрузочном тестировании графена, проведенного Rudex в свое время. Надо найти ссылку на их сайте, или на Bitsharestalk.org
