### ISSUE TITLE
Реализация методов взаимодействия акторов

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#20]
Реализация работы акторов в симуляторе, не включающая бизнес логику. Задача по дальнейшей разработки движка симулятора.

**Comment by codename-art** [comment]
@kkrupovich беру эту задачу на день.
BLOCK #24155063

TRANSFER |  
-- | --
From | codename-art
To | cptn-solo
Quantity | 90.00000 UTDEV.SKILL
Проверка | 05.02 вечером

P.S. Написал комментарий еще утром, но не отправил

**Comment by codename-art** [comment]
Добавил механизм задач для акторов. По задумке, это позволит описать логику работы акторов в виде цепочки задач, которые будут переключаться по таймауту или по получению определенных транзакций.

**Comment by kkrupovich** [comment]
@codename-art 
BLOCK #24170771

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
