### ISSUE TITLE
Реализация внешнего API на субд для тестирования

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#22]
Продолжение #13
Тестировочный вариант #21

**Comment by codename-art** [comment]
@kkrupovich беру задачу на 3 дня
BLOCK #24387042

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 270.00000 UTDEV.SKILL
проверка | 15.02 вечером

**Comment by codename-art** [comment]
Добавлена реализация интерфейса работы с блокчейном, которая выполняет работает поверх реляционной СУБД. Добавлены тесты на работу API.

**Comment by cptn-solo** [comment]
@codename-art 
BLOCK #24469948

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 270.00000 UTDEV

**Comment by cptn-solo** [comment]
@codename-art закроем после созвона по [pull#31](https://github.com/u-transnet/transnet-simulator/pull/31)
