### ISSUE TITLE
Реализация бизнес логики акторов

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#23]
Продолжение задачи #20 
Используя механизм задач акторов, описать работу клиента и логиста.

**Comment by codename-art** [comment]
@kkrupovich Беру задачу на завтра
BLOCK #24170167

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 06.02 вечером

**Comment by codename-art** [comment]
@kkrupovich Сделал основную часть задачи, но невозможно завершить без #12

**Comment by codename-art** [comment]
@kkrupovich Реализовал взаимодействие клиента и логиста, и отчасти действие клиента со станцией.
Пока задачу не закрываю, есть две проблемы: откуда клиент узнает о логисте и стоимость его работы #26

**Comment by kkrupovich** [comment]
@codename-art paid? поправил на skilled. Предлагаю скилл компенсировать, задачу закроем по факту, возможно с доскиловкой и доп. компенсацией?

**Comment by codename-art** [comment]
@kkrupovich действительно, я ошибся с тегами.
Завтра закрою #26 и эту сразу, тут дорабатывается легко.

**Comment by codename-art** [comment]
Для симулятора ограничились тем, что на этапе создание объекта клиента ему передается имя логиста и стоимость его работы. Задачу можно закрывать.

**Comment by kkrupovich** [comment]
@codename-art 
BLOCK #24249737

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
