### ISSUE TITLE
Тесты и документация механизма акторов

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#24]
Тесты и документация механизма акторов, включая Supervisor и ActorTask

**Comment by codename-art** [comment]
@kkrupovich Беру задачу на 3 дня
BLOCK #24241413

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 270.00000 UTDEV.SKILL
Проверка | 12.02 вечером

**Comment by kkrupovich** [comment]
@netral23 предлагаю после завершения этой задачи провести вместе с @codename-art ревью

**Comment by cptn-solo** [comment]
@codename-art 
BLOCK #24422003

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 270.00000 UTDEV
