### ISSUE TITLE
Задача выбора логиста клиентом в симуляторе

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#26]
Откуда Клиент узнает адрес логиста и стоимость его работы?

**Comment by kkrupovich** [comment]
@codename-art помнишь, мы говорили, что это одна из бизнес-моделей, функционирующей поверх платформы? Это в буквальном смысле аналог booking.com - только в другой прикладной области. Сайт и приложение, разрабатываемое и продвигаемое логистом. Прейскуранты, конкуренция, вот это все. Т.о. в рамках симуляции это входной параметр. 
PS: в этой истории интересно другое - пользователь может и сам бронировать ресурсы точек транзита через общедоступные API и тем самым "совершить диверсию" или "выкупить все таймслоты" или сделать что-то подобное. Нужно будет проанализировать этот аспект и предложить какое-то решение. `TBD`

**Comment by codename-art** [comment]
@kkrupovich Согласен, для симулятора можно ограничиться входным параметром, работа логиста включена в симулятор, только для создания резервов.

Для защиты можно использовать инструмент черного и белого списка на ОФИ. На это есть задача. Как только закончу с первой частью задач по кодингу, где к архитектурк вопросов нет, Пойдет новая итерация доработки архитектуры.

**Comment by kkrupovich** [comment]
@codename-art 
> черного и белого списка на ОФИ

Согласен. Это, кстати, дает весьма интересный выход на бизнес-модель оператора адресного проекта - логист может быть включен им в белый список при условии, например, наличия токена адресного проекта или направления. Косвенно - это подтверждает модель концессии @alecvert

**Comment by codename-art** [comment]
Для симулятора ограничились тем, что на этапе создание объекта клиента ему передается имя логиста и стоимость его работы. Задачу можно закрывать.
