### ISSUE TITLE
Создание базовых классов, парсинг json сценария.

### ISSUE THREAD

**Issue by UspenskyDritry** [u-transnet/transnet-simulator#3]

**Comment by UspenskyDritry** [comment]
BLOCK #22424976 USPENSKYDMITRY1970 125UTDEV.SKILL до вечера 07 ноября 2017

**Comment by kkrupovich** [comment]
@UspenskyDritry см. #1 - ты торопишься программировать. Проскиллуй #1 тоже на сегодня, тебе тогда на два дня хватит работы (и на выходные ИМХО тоже, если начинать с кодинга)

**Comment by codename-art** [comment]
Продолжение в #11 и #12
