### ISSUE TITLE
проработка абстракции Proposal

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#32]
Так как нет необходимости полной реализации блокчейна в  ExternalAPI, следует использовать абстракцию Proposal вместо отдельных операций PROPOSAL_CREATE_OPERATION и PROPOSAL_UPDATE_OPERATION.

В связи с этим надо пересмотреть работу акторов с proposal

**Comment by codename-art** [comment]
@kkrupovich 
BLOCK #24484296

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 16.02 вечером

Вечером обсудить не успели, задача готова, при следующем совещании обсудим.

**Comment by ishmelev23** [comment]
[Ссылка](http://docs.bitshares.org/api/websocket.html) на нотификации в Graphene

**Comment by codename-art** [comment]
Подписка на обновления - очень полезная возможность. Pybitshares тоже поддерживает [уведомления](http://docs.pybitshares.com/en/latest/websocket.html?highlight=push) Но везде слабовато с документацией, надо опробовать это в деле #36

**Comment by cptn-solo** [comment]
@codename-art 
BLOCK #24768427

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
