### ISSUE TITLE
Рефакториг ActorTask для поддержки событий Proposal

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#35]
Продолжение #32 
В связи с изменение формата обновления состояния proposed transaction, необходимо доработать ActorTask для поддержки новых событий

**Comment by codename-art** [comment]
@kkrupovich беру задачу на день
BLOCK #24565027

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 19.02 вечером

**Comment by codename-art** [comment]
Добавлен новый слой абстракции, который содержит в себе объект блокчейна, который вызвал событие. Был введен чтобы унифицировать события транзакций и обновления Proposal.

Пулл реквест можно будет создать после слияния #38

**Comment by cptn-solo** [comment]
@codename-art 
BLOCK #24768471

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
