### ISSUE TITLE
Изучение уведомлений в графене

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#36]
Graphene имеет [возможность](http://docs.bitshares.org/api/websocket.html) подписки на изменения объектов. Pybitshares тоже поддерживает [уведомления](http://docs.pybitshares.com/en/latest/websocket.html?highlight=push). Но везде слабовато с документацией, надо опробовать это в деле.

На практике, с помощью Pybitshares, изучить работу данного механизма.

**Comment by codename-art** [comment]
@kkrupovich беру задачу на день
BLOCK #24587245

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | вечером 20.02

**Comment by codename-art** [comment]
Итого, с помощью данного механизма можно получить информацию о новых операциях заданного аккаунта. Ниже привожу пример получение уведомлений для аккаунта codename-art.
1. Подписка на оповещения:

```python
ws = BitSharesWebsocket(
    "wss://bitshares.openledger.info/ws",
    accounts=["codename-art", "alex-pipkin", "trans.bot", "btsshr"],
    on_account=on_account,
)
```
2. В колбэк on_account передается объект [bitshares.notify.Notify](http://docs.pybitshares.com/en/latest/notify.html#bitshares.notify.Notify)
следующего формата
```
{
‘id’: ‘2.6.29’,
‘lifetime_fees_paid’: ‘44261516129’,
‘most_recent_op’: ‘2.9.0’,
‘owner’: ‘1.2.29’,
‘pending_fees’: 0,
‘pending_vested_fees’: 16310,
‘total_core_in_orders’: ‘6788845277634’,
‘total_ops’: 0
}
```

3. Данный колбэк вызывается с Notify не только желаемого аккаунта, предполагаю, это изменения, которые попали в этот же блок. По этому следующем шагом, необходимо отсеять обновления касающиеся желаемого аккаунта.

4. Notify содержит id аккаунта, для получения имени необходимо использовать объект [ bitshares.account.AccountUpdate](http://docs.pybitshares.com/en/latest/account.html#bitshares.account.AccountUpdate)

```python
update = AccountUpdate(notice)
update.account.name
```

5. Полную операцию, которая вызвала обновление аккаунта можно получить с помощью дополнительных вызовов api блокчейна.

5.1. account_transaction_history_object
```python
most_recent_op = bitshares.rpc.get_objects([notice['most_recent_op']])[0]
```

5.2. account_statistics_object
```python
hist_obj = bitshares.rpc.get_objects([most_recent_op['operation_id']])[0]
```

6. Из account_statistics_object уже можно получить искомую операцию:
```python
hist_obj['op'][1]
```


Итоговый скрипт для получения обновлений (добавил случайные аккаунты для получения обновлений, чтобы пришлось меньше ждать):
```python
from pprint import pprint

from bitshares.account import AccountUpdate
from bitshares.blockchain import Blockchain
from bitsharesapi.websocket import BitSharesWebsocket
from bitsharesbase.operations import getOperationNameForId

chain = Blockchain()
bitshares = chain.bitshares

def on_account(notice):
    print("-----------------------------------------------------")
    update = AccountUpdate(notice)
    print(update.account.name)
    most_recent_op = bitshares.rpc.get_objects([notice['most_recent_op']])[0]
    hist_obj = bitshares.rpc.get_objects([most_recent_op['operation_id']])[0]
    print(getOperationNameForId(hist_obj['op'][0]))
    pprint(hist_obj['op'][1])
    print("-----------------------------------------------------")
    return


ws = BitSharesWebsocket(
    "wss://bitshares.openledger.info/ws",
    accounts=["codename-art", "alex-pipkin", "trans.bot", "btsshr"],
    on_account=on_account,
)

ws.run_forever()
```

Пример полученной операции из обновления:
```
-----------------------------------------------------
btsshr
limit_order_create
{'amount_to_sell': {'amount': 4000001, 'asset_id': '1.3.0'},
 'expiration': '2023-02-19T19:00:00',
 'extensions': [],
 'fee': {'amount': 92, 'asset_id': '1.3.0'},
 'fill_or_kill': False,
 'min_to_receive': {'amount': 100080, 'asset_id': '1.3.121'},
 'seller': '1.2.475780'}
-----------------------------------------------------
```

**Comment by codename-art** [comment]
@kkrupovich Механизм уведомлений о транзакциях следует включить в наш ExternalAPI #37

**Comment by codename-art** [comment]
@netral23 правильно напомнил, что транзакции могут быть неподтвержденными, но это отдельный шаг, для проверки их статуса.

**Comment by cptn-solo** [comment]
@codename-art 
BLOCK #24618261

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
