### ISSUE TITLE
Внедрить механизм push уведомлений об изменениях в графене в ExternalAPI

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#37]
Продолжение #36 
Добавить возможность использования уведомлений в ExternalAPI.
Можно использовать два типа уведомлений:
1. Уведомление об изменении с идентификатором, но без дополнительных запросов.
2. Подписка с колбэком на уведомление, при этом в колбэк сразу передается объект вызвавший изменение.

**Comment by codename-art** [comment]
@kkrupovich беру задачу на день
BLOCK #24615713

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка | 21.02 вечером

**Comment by codename-art** [comment]
Добавил два механизма уведомлений и сделал реализацию для H2 с тестами.
* listenAccountUpdates - добавляет колбэк, который при обновлении получает общее количество операций совершенных данным аккаунтом, и объект аккаунта, который обновился.
* listenAccountOperations - добавляет колбэк, который при обновлении получает объект, который вызвал обновление аккаунта, например Proposal и TransferOperation

**Comment by cptn-solo** [comment]
@codename-art реализация этого для Bitshares недавно где-то была сделана чуть ли не в opensource - в чате Rudex обсуждался бот для отслеживания аккаунтов "китов" - и его в итоге сделали 👍 

BLOCK #24658000

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
