### ISSUE TITLE
Тесты для Client

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#39]
Протестировать созданные на данный момент задачи Client, такие как заказ маршрутной карты, заказ вагона и т.п.

**Comment by codename-art** [comment]
@kkrupovich беру задачу на день
BLOCK #24643133

TRANSFER |  
-- | --
From | codename-art
To | utd-front
Quantity | 90.00000 UTDEV.SKILL
Проверка  | вечером 22.02

**Comment by codename-art** [comment]
@kkrupovich покрыл тестами основной механизм событий и лисенеров транзакций. Еще необходимо будет протестировать работу с маршрутной картой, но на данной момент еще не все готово для ее работы. На это надо будет создать отдельную задачу. 
PR создам позже, после слияния предыдущих.

**Comment by cptn-solo** [comment]
@codename-art 
BLOCK #24657936

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 90.00000 UTDEV
