### ISSUE TITLE
Навести порядок в репозитории

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#8]
- Провести ревизию текущих задач.

- Создать новые задачи, стараясь делать их менее обширными.

- Добавить дашборд для задач.

**Comment by codename-art** [comment]
@kkrupovich 
BLOCK #23955270

TRANSFER 
From | codename-art
To | utd-front
Quantity | 75.00000 UTDEV.SKILL
Проверка 29.01 вечером

**Comment by codename-art** [comment]
@kkrupovich 

Почистил [доску проекта](https://github.com/u-transnet/transnet-simulator/projects/1), в ней задачи разделены по направления разработки.

Добавил [доску с текущей работой](https://github.com/u-transnet/transnet-simulator/projects/2), в ней буду задачи которые заскиллованы или ждут ревью.

Добавил новые лейблы для задача: blocking (блокируют другие задачи) и blocked (другие задачи мешают решить эту).

А так же создал новые задачи на ближайшее время и преобразовал несколько старых.

**Comment by kkrupovich** [comment]
@codename-art  👍 

BLOCK #23970422

TRANSFER |  
-- | --
From | utd-front
To | codename-art
Quantity | 75.00000 UTDEV
