### ISSUE TITLE
Сделать форк graphenej

### ISSUE THREAD

**Issue by codename-art** [u-transnet/transnet-simulator#9]
Сделать форк Android библиотеки https://github.com/Agorise/graphenej и перевести ее на JDK

**Comment by codename-art** [comment]
Форк готов. Пока изменения в [ветке jdk](https://github.com/u-transnet/graphenej/tree/jdk)

**Comment by codename-art** [comment]
@kkrupovich в библиотеки реализовано далеко не все, что нам понадобится, так что еще будут задачи по доработке и публикации. Но эти задачи создам в том репозитории.

**Comment by kkrupovich** [comment]
@codename-art как думаешь, тебе помог бы диалог с командой, параллельно занимающейся железом и формирующей перечень необходимых интерфейсов? Или делаем сначала софт? Надо может будет вообще собраться и пообсуждать возможный облик технологического прототипа - как именно он будет взаимодействовать с блокчейном - для @Arteg0r это тоже будет кстати интересно.

**Comment by codename-art** [comment]
@kkrupovich от этого определенно польза будет. Но это не касается непосредственно работы с графеном. Эти вызовы симулируются внутри симулятора.
